### ISSUE TITLE
[skillscrollicon] マウス操作時に右上のアイコンをクリックしても反応しない

### ISSUE THREAD

**Issue by kajikum** [writ312/myTosAddons#1]
バグなのかどうか分からないですが、右上のスキルアイコンをクリックしても何も起きません。  
これは仕様ですかね？

**Comment by writ312** [comment]
ただのアイコンだからなぁ
発動するようにセットしたほうがいいかな？

**Comment by kajikum** [comment]
うーん、どれだけ需要があるのかどうかは知らないですけど、もし他にもいるようだったら対応するぐらいのスタンスでいいと思いますよ

**Comment by writ312** [comment]
これ実はかなり厳しいことがわかった
多分slotでやってるのがいけないのでpictureとかでやればいいっぽい

**Comment by writ312** [comment]
修正済み
