### ISSUE TITLE
Quick menu not working =(

### ISSUE THREAD

**Issue by rods321** [writ312/myTosAddons#12]
Can you fix it ?

**Comment by writ312** [comment]
In Japan, it's working.
Ktos? iTos?

**Comment by writ312** [comment]
どういった部分が動かないのか？
起動しない？
F10またはコマンドを打ってもウィンドウが表示されない？
メニューを実行できない？
詳しい情報を求む

What parts do not move?
It does not start?
Window does not appear even if you type F10 or command?
Can not execute the menu?
Request more information

**Comment by writ312** [comment]
返事がないようなので一旦閉じます。
何かあればまた開いてください
