### ISSUE TITLE
Trace Mode & Click Through

### ISSUE THREAD

**Issue by Planeswalkers86** [writ312/myTosAddons#15]
Trace Mode resets everytime you change map.

WTB Click Through Mode for Mouse Mode

**Comment by writ312** [comment]
Thank you for open issue. :)
I fix it.
please update this addon.

**Comment by Planeswalkers86** [comment]
I need to buy you a drink or something, THANK YOU for those fixes!

**Comment by writ312** [comment]
Please contact me if anything happens.　( ´∀｀)
