### ISSUE TITLE
Hotkey Ability for Joystick

### ISSUE THREAD

**Issue by NoctisCepheus** [writ312/myTosAddons#16]
The addon does not work properly. dragging from macro window to hotkeys are not working. would appreciate it if it got fixed. thank you

**Comment by writ312** [comment]
Is it the case of Discord?   
Is it after ReBuild?   
I'll investigate.

**Comment by NoctisCepheus** [comment]
Seems like after rebuild. Heres what i gathered from testing it:
1. Dragging from the chat macro to an empty hotkey wont work. It wont even create the json file on the folder under the "addon" folder. 
2. Dragging from the chat macro to an occupied hotkey works. It creates the json file. But now, both the item/skill it replaced and the chat macro is executed instead of the chat macro overwriting the item/skill
3. Manually making the json file on the "addon" folder makes it work but there wont be an icon and you wont be able to remove or replace it unless you manually edit the json file.

**Comment by writ312** [comment]
c24a355de3163d30ad3e8a56235955b366e24b33
3e3ab73bbf24b16626671e91befc23d32de2cd3e
