### ISSUE TITLE
Hotkey Ability for Joy

### ISSUE THREAD

**Issue by NoctisCepheus** [writ312/myTosAddons#17]
I found a new bug. When you cast a buff/stance type skill, the icon of the chat macro (the white box with 1, 2, 3, 4, . . . ) in the hotkey when using joysticks disappear. it still works even if the icon is gone and reappears if you change channel.

**Comment by writ312** [comment]
Ok understood.
 I plan to work right away, but I do not have a character that uses stance skills.

**Comment by writ312** [comment]
Please review after updating

**Comment by writ312** [comment]
@NoctisCepheus I updated addon, please check it

**Comment by NoctisCepheus** [comment]
Ok. Thank you for fixing it. The icons dont disappear anymore but they do
flicker(disappear then reappear) whenever i cast a buff/stance skills. I
guess your workaround was to refresh the icon generator everytime you cast
a buff skill? But it does work. It just flickers when you cast a buff.
Thank you very much for fixing it asap :)

**Comment by writ312** [comment]
Although it is possible, it is likely to collide with other add-ons
In that case, this add-on is not a solution to the problem
