### ISSUE TITLE
[Resource Manager Lite] Add option to show arrow craft material

### ISSUE THREAD

**Issue by calendulish** [writ312/myTosAddons#2]
Do you could add woods (arrow craft material - Pine, Cedar, Oak, Ash) to fletcher ui too? or a option to enable this? So will be possible to know when has no more materials.

Thank you

**Comment by writ312** [comment]
thank you for issue
of course.  add materials is easy.
please wait few days. I`ll update the addon.

**Comment by writ312** [comment]
I'm really sorry for the late reply.
I just pushed a commit.
Please update the addon with Addon Manager jp.
Thank you (*´∀｀*)

**Comment by calendulish** [comment]
When log-in everything is right, but after changing map, I just see wood materials, the first item block disapear

**Comment by writ312** [comment]
thank you :)
just fixed this bugs
please update this addon
(*´∀｀*)
