### ISSUE TITLE
Barrack Itemlist English version

### ISSUE THREAD

**Issue by bsides** [writ312/myTosAddons#3]
Hi! I just translated some Korean from your addon in Google Translator, compiled and looks like it works. Would you like to release it as an english version? It's on my [fork.](https://github.com/bsides/myTosAddons) There's possible a better way to do this but for now it's working... so let me know (or just release it). Thank you! 👍

**Comment by writ312** [comment]
I am sorry for the late reply.
I have been a little busy lately.
I confirmed your repository and I tried it.
I plan to release it as an English version immediately.
Thank you.

**Comment by writ312** [comment]
ok
Add Barrack Item List English ver with manager
thank you for your issue (*´∀｀*)

**Comment by bsides** [comment]
I was just posting my version in the forums then I decided to see if you answered. Thank you! I believe it'd be a great addition. Also, I fixed the search since in ocidental characters, the capitals matter so I lowercase all before sending the search. I hope it's fine :)

Thanks again!

PS - If you need me translating anything else let me know. Also, If you guys have a community (in english) for addon talk let me know. I would like to develop some too.

**Comment by writ312** [comment]
Thank you.
Because I am not good at English, I am using google translation.
So it may be a little confusing.

As for lowercase letters, is it advising that I should do so when I develop something similar?
I understood that :)

Sorry about the community.
I only know things in Japanese.
However, I think that there is no problem speaking in English, so I will paste the URL.
Since I am in consultation if it is ok with me (¯ ー ¯)
[Gitter room](https://gitter.im/JTosAddon/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link)

**Comment by bsides** [comment]
It's fine @writ312 thank you very much! English is not my first language either so we are trying our best :) I am joining this gitter room but I believe I couldn't enjoy so much since I don't know japanese. I will try it anyway. Regards from Brazil!

**Comment by bsides** [comment]
About the capitalization: I believe you didn't do it before because in japanese it's not needed right? Just curious.

**Comment by writ312** [comment]
In gitter room, you dont need Japanese.
you can use English.
Dont worry
We are always welcoming new colleagues

**Comment by writ312** [comment]
About the capitalization.
You right
In Japan,three kinds of words.
Hiragana ,Katakana ,Kangi.
But their relationships are different from English upper case letters and lower case letters.
They are independent languages.
So we don't use lower or upper function.
