### ISSUE TITLE
Wrong path

### ISSUE THREAD

**Issue by RSPadilha** [writ312/myTosAddons#4]
Line 5 g.settingPath = '../addons/barrackitemlist/'
isn't g.settingPath = '../addons/barrackitemlist_eng/' ?
The addon can not find the correct path, I did need to change the folder name to barrackitemlist and manually create the setting.json and userlist.json files

**Comment by writ312** [comment]
そうだね
一度もbarrack item listを使ったことがないとすると、そうする必要がある
初めてこのアドオンを使うことは想定してなかった

**Comment by writ312** [comment]
気が向いたら修正するが、期待はしないでほしい
ユーザーの努力で修正可能であれば、私はそうするべきだと考えてるからだ

**Comment by writ312** [comment]
Thank you
I fixed description
Maybe I will fix addon next week.
