### ISSUE TITLE
Make use of acutil.addSysIcon() for addons that use sysicons.

### ISSUE THREAD

**Issue by MizukiBelhi** [writ312/myTosAddons#5]
Because it's a thing now and to prevent filling up the sysmenu with buttons.
acutil gets automatically downloaded when you install an addon through the addon manager so there shouldn't be any issues (as long as, you know, you only release it for download through the addon manager).

お願いします

**Comment by writ312** [comment]
Thank you for adding functionality
I will implement it with this add-on that I publish
Including correction of acutil was very helpful

Sorry about the Google translation

**Comment by writ312** [comment]
I will update 10/24

**Comment by MizukiBelhi** [comment]
Please let other developers know too.
他の開発者にも知らせてください

**Comment by writ312** [comment]
Sorry for being late
I updated addons
Thanks(｡>﹏<｡)
