### ISSUE TITLE
The icon spacing is far away.

### ISSUE THREAD

**Issue by okmoon** [writ312/myTosAddons#6]
I installed Barrack Item List and ExtendUI 2-Pre today.
But the spacing of the icons is too far away.
Can you reduce the spacing?
Thanks for making nice addons.
![1](https://user-images.githubusercontent.com/19366475/33058627-d54d8742-ced3-11e7-9f9c-83ee78402442.png)

**Comment by writ312** [comment]
I updated addon
Please try to check 😀

**Comment by okmoon** [comment]
It's so clean! 
Thank you!
