### ISSUE TITLE
[muteki2ex] Buffs bought from pardoner shops always display on every map change

### ISSUE THREAD

**Issue by Xanaxiel** [writ312/myTosAddons#9]
When buying buffs from a pardoner, blessing and aspersion always have their gauges shown. I think for these buffs, it would be best to show them if the duration is < 1min left

![image](https://user-images.githubusercontent.com/19189593/40260467-5b83f950-5b2d-11e8-8c53-3e3e4a77564a.png)

**Comment by writ312** [comment]
対応したよー

**Comment by Xanaxiel** [comment]
どうもありがとう！muteki2の素晴らしい

Teach me Japanese :D
